const express = require('express');
//const variables cannot be reassigned to
const hbs = require('hbs');

//setup app
const app = express();

//setup express to use hbs
app.set('view engine', 'hbs')


//setup express to define where to find static files(not generated by js/programming; dynamic is);
app.use(express.static('public'));

//routes are defined before starting server
//req should always be before res
app.get('/', function(req, res){
    //if no res; then the browser will keep loading since it is waiting for a response
    //do not reture/console.log from route function unless you want to end the function
    //route function must eventually have a res.send
    res.render('index')
})

app.get('/hello/:name', function(req,res){
    let name = req.params.name;
    res.render('hello', {
        //the key is the variable name
        'name' : name
    })
})

//start server at port 3000
app.listen(3000, function (){
    console.log('server started');
})